package com.localagent.business.auth;

import com.localagent.business.auth.AuthDtos.*; import com.localagent.business.user.*;
import com.nimbusds.jose.*; import com.nimbusds.jose.crypto.RSASSASigner; import com.nimbusds.jwt.*;
import java.nio.charset.StandardCharsets; import java.security.*; import java.time.Instant; import java.util.*;
import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class AuthService {
  private final UserRepository users; private final RefreshSessionRepository refreshes; private final PasswordEncoder passwords; private final AuthProperties p; private final RsaKeyMaterial keys; private final EmailVerificationService verification; private final SecureRandom random=new SecureRandom();
  public AuthService(UserRepository u,RefreshSessionRepository r,PasswordEncoder pe,AuthProperties p,RsaKeyMaterial k,EmailVerificationService verification){users=u;refreshes=r;passwords=pe;this.p=p;keys=k;this.verification=verification;}
  public static String normalize(String email){return email.strip().toLowerCase(Locale.ROOT);}
  @Transactional(noRollbackFor=InvalidVerificationCodeException.class) public AuthResponse register(RegisterRequest req){String email=normalize(req.email()); if(users.findByNormalizedEmail(email).isPresent())throw new AuthException("email_already_registered","该邮箱无法注册。",HttpStatus.CONFLICT); verification.verifyAndConsume(email,req.verificationCode()); Instant now=Instant.now(); UserEntity u=new UserEntity();u.setId(UUID.randomUUID());u.setNormalizedEmail(email);u.setPasswordHash(passwords.encode(req.password()));u.setDisplayName(req.displayName().strip());u.setStatus("ACTIVE");u.setEmailVerified(true);u.setCreatedAt(now);u.setUpdatedAt(now);users.save(u);return issue(u,req.deviceId(),UUID.randomUUID());}
  @Transactional public AuthResponse login(LoginRequest req){String email=normalize(req.email()); UserEntity u=users.findByNormalizedEmail(email).orElse(null); if(u==null||!passwords.matches(req.password(),u.getPasswordHash())||!"ACTIVE".equals(u.getStatus()))throw new AuthException("invalid_credentials","邮箱或密码不正确。",HttpStatus.UNAUTHORIZED);return issue(u,req.deviceId(),UUID.randomUUID());}
  @Transactional(noRollbackFor=AuthException.class) public AuthResponse refresh(String raw,String deviceId){if(raw==null||raw.isBlank())throw invalidRefresh(); String hash=hash(raw); RefreshSessionEntity old=refreshes.findByTokenHashForUpdate(hash).orElseThrow(this::invalidRefresh); Instant now=Instant.now(); if(old.getRevokedAt()!=null){refreshes.revokeFamily(old.getTokenFamilyId(),now);throw new AuthException("refresh_reuse_detected","刷新凭据已失效，请重新登录。",HttpStatus.UNAUTHORIZED);} if(old.getExpiresAt().isBefore(now)||!MessageDigest.isEqual(old.getDeviceId().getBytes(StandardCharsets.UTF_8),deviceId.getBytes(StandardCharsets.UTF_8))){old.setRevokedAt(now);refreshes.save(old);throw invalidRefresh();} String nextRaw=randomToken();RefreshSessionEntity next=newSession(old.getUser(),nextRaw,deviceId,old.getTokenFamilyId(),now);refreshes.save(next);old.setRevokedAt(now);old.setLastUsedAt(now);old.setReplacedBy(next.getId());refreshes.save(old);return response(old.getUser(),nextRaw);}
  @Transactional public void logout(String raw){if(raw==null||raw.isBlank())return;refreshes.findByTokenHash(hash(raw)).ifPresent(s->{if(s.getRevokedAt()==null){s.setRevokedAt(Instant.now());refreshes.save(s);}});}
  private AuthResponse issue(UserEntity u,String deviceId,UUID family){String raw=randomToken();refreshes.save(newSession(u,raw,deviceId,family,Instant.now()));return response(u,raw);}
  private RefreshSessionEntity newSession(UserEntity u,String raw,String deviceId,UUID family,Instant now){RefreshSessionEntity s=new RefreshSessionEntity();s.setId(UUID.randomUUID());s.setUser(u);s.setTokenHash(hash(raw));s.setTokenFamilyId(family);s.setDeviceId(deviceId);s.setExpiresAt(now.plus(p.refreshTtl()));s.setCreatedAt(now);return s;}
  private AuthResponse response(UserEntity u,String refresh){Instant exp=Instant.now().plus(p.accessTtl());return new AuthResponse(access(u,exp),refresh,exp,profile(u));}
  UserProfile profile(UserEntity u){return new UserProfile(u.getId(),u.getNormalizedEmail(),u.getDisplayName(),u.getStatus(),u.isEmailVerified(),List.of("USER"));}
  private String access(UserEntity u,Instant exp){try{Instant now=Instant.now();JWTClaimsSet claims=new JWTClaimsSet.Builder().issuer(p.issuer()).audience(p.audience()).subject(u.getId().toString()).claim("roles",List.of("USER")).issueTime(Date.from(now)).expirationTime(Date.from(exp)).jwtID(UUID.randomUUID().toString()).build();SignedJWT jwt=new SignedJWT(new JWSHeader.Builder(JWSAlgorithm.RS256).keyID(keys.kid()).type(JOSEObjectType.JWT).build(),claims);jwt.sign(new RSASSASigner(keys.privateKey()));return jwt.serialize();}catch(JOSEException e){throw new IllegalStateException("Unable to sign access token",e);}}
  private String randomToken(){byte[] b=new byte[32];random.nextBytes(b);return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
  private String hash(String raw){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
  private AuthException invalidRefresh(){return new AuthException("invalid_refresh_token","刷新凭据无效或已过期，请重新登录。",HttpStatus.UNAUTHORIZED);}
}
